name: CI
on: [push, pull_request]

#env:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - run: mdbook build

      - run: zip -r book.zip book
      - uses: actions/upload-artifact@v2
        with:
          name: book.zip
          path: ./book.zip
