name: CI
on: [push, pull_request]

env:
  MDBOOK_VERSION: v0.4.13

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      # setup mdbook
      - run: curl -o mdbook-x86_64-linux.tar.gz https://github.com/rust-lang/mdBook/releases/download/${{ env.MDBOOK_VERSION }}/mdbook-${{ env.MDBOOK_VERSION }}-x86_64-unknown-linux-gnu.tar.gz
      - run: tar -xf mdbook-x86_64-linux.tar.gz
      # TODO
      - run: ls -al .
      - run: ls -al mdbook-x86_64-linux

      # TODO
      - run: mdbook --version
      - run: mdbook build

      - run: zip -r book.zip book
      - uses: actions/upload-artifact@v2
        with:
          name: book.zip
          path: ./book.zip
